modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
credits="Thanks for this example mod goes to Java" #optional
authors="Love, Cheese and small house plants" #optional

[[mods]] #mandatory
modId="examplemod" #mandatory
version="0.0.1 " #mandatory
displayName="Test piotr mod 1" #mandatory
description='''
This is a simple test
My version 1 
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.examplemod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[25,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"